
language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to 5.3.29
  #- 5.3
  # aliased to a recent 5.4.x version
  #- 5.4
  # aliased to a recent 5.5.x version
  #- 5.5
  # aliased to a recent 5.6.x version
  #- 5.6
  # aliased to a recent 7.x version
  - 7.0
  # aliased to a recent hhvm version
  #- hhvm

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql

# optionally set up exclutions and allowed failures in the matrix
matrix:
  exclude:
    - php: hhvm
      env: DB=pgsql  # PDO driver for pgsql is unsupported by HHVM (3rd party install for support)
  allow_failures:
    - php: 7.0
    - php: hhvm


before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "CREATE DATABASE IF NOT EXISTS abantecart_test_build;" -uroot; fi
  - php ./public_html/install/cli_install.php install --db_host=localhost --db_user=root --db_password= --db_name=abantecart_test_build  --db_driver=amysqli  --db_prefix=abc_ --admin_path=admin  --username=admin  --password=admin  --email=abolabo@gmail.com  --http_server=http://abolabo.hopto.org/github/129/public_html --with-sample-data

script:
  - phpunit -c tests/phpunit/phpunit_$DB.xml

after_script:
  - echo "Hello World"

notifications:
  email:
    recipients:
      - dsuprunenko@abantecart.com
     #- projkov@abantecart.com
  on_success: always
  on_failure: always